# Generated by Django 3.1.3 on 2020-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0002_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('overallGainedScore', models.IntegerField()),
                ('overallPossibleScore', models.IntegerField()),
                ('overallPercent', models.FloatField()),
                ('mathGainedScore', models.IntegerField()),
                ('mathPossibleScore', models.IntegerField()),
                ('mathPercent', models.FloatField()),
                ('historyGainedScore', models.IntegerField()),
                ('historyPossibleScore', models.IntegerField()),
                ('historyPercent', models.FloatField()),
                ('geographyGainedScore', models.IntegerField()),
                ('geographyPossibleScore', models.IntegerField()),
                ('geographyPercent', models.FloatField()),
                ('computersGainedScore', models.IntegerField()),
                ('computersPossibleScore', models.IntegerField()),
                ('computersPercent', models.FloatField()),
                ('biologyGainedScore', models.IntegerField()),
                ('biologyPossibleScore', models.IntegerField()),
                ('biologyPercent', models.FloatField()),
                ('literatureGainedScore', models.IntegerField()),
                ('literaturePossibleScore', models.IntegerField()),
                ('literaturePercent', models.FloatField()),
                ('mixedGainedScore', models.IntegerField()),
                ('mixedPossibleScore', models.IntegerField()),
                ('mixedPercent', models.FloatField()),
            ],
        ),
    ]
