# Generated by Django 3.1.3 on 2020-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0004_auto_20201230_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Double',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=300)),
                ('player1score', models.IntegerField()),
                ('player2', models.CharField(max_length=300)),
                ('player2score', models.IntegerField(default=None)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('winner', models.CharField(default=None, max_length=300)),
                ('complete', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('gainedScore', models.IntegerField(default=0)),
                ('possibleScore', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
            ],
        ),
    ]
