# Generated by Django 3.1.3 on 2020-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0005_double_doubleleaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='double',
            name='player2score',
            field=models.IntegerField(default=0),
        ),
    ]
