# Generated by Django 3.1.3 on 2020-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0006_auto_20201231_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='double',
            name='complete',
        ),
        migrations.AlterField(
            model_name='double',
            name='winner',
            field=models.CharField(default='nobody', max_length=300),
        ),
    ]
