# Generated by Django 3.1.3 on 2020-12-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0007_auto_20201231_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='double',
            name='time',
        ),
    ]
